site_name: HubZhangxj Blog 
site_author: hubzhangxj

repo_url: https://github.com/hubzhangxj/hubzhangxj-blog
use_directory_urls: true
nav:
    - Home: index.md
    - Benchmark:
        - speccpu2006: benchmark/speccpu2006.md
        - sysbench: benchmark/sysbench.md
        - fio: benchmark/fio.md
        - vdbench: benchmark/vdbench.md
        - iperf: benchmark/iperf.md
        - stream: benchmark/stream.md
        - unixbench: benchmark/unixbench.md
        - perf: benchmark/perf.md
    - Big data:
        - HDFS: big-data/hdfs.md 
        - MapReduce: big-data/mapreduce.md
        - YARN: big-data/yarn.md
        - Hbase: big-data/hbase.md
        - Hive: big-data/hive.md
    - SQL :
        - MySQl: sql/mysql.md
        - Postgis: sql/postgis.md
        - PostgreSQl: sql/postgres.md
    - Kernel:
        - Mem: mem.md
        - Mutex: mutex.md
        - Interrupt: interrupt.md
        - IO Subsystem: io.md
        - NetWork Subsystem: network.md
    - About: about.md
theme: readthedocs

